### ISSUE TITLE
[MVP] 마크업

### ISSUE THREAD

**Issue by jinsunee** [Febase/react-motion-float-button#4]
# 설명
Floating Button을 눌렀을 때 직선으로 메뉴가 열리는 버튼 구현
![image](https://user-images.githubusercontent.com/31176502/107322348-a305fb80-6ae7-11eb-8c8c-c476b9070cf4.png)

# 목표 및 방향성
- 최대한 커스터마이징이 쉬운 방향
- 열리는 방향 
   - Direction.TOP
   - Direction.BOTTOM
   - Direction.LEFT 
   - Direction.RIGHT

**Comment by tjdud0123** [comment]
1차 마크업 완성
![image](https://user-images.githubusercontent.com/22907830/107784638-08c7e100-6d8f-11eb-88de-2fcc79af6776.png)
