### ISSUE TITLE
Rollup + Emotion 이슈

### ISSUE THREAD

**Issue by chjjh0** [Febase/react-motion-float-button#7]
기본설정과 devServer로 실행 가능한 레포를 만들었으며 clone하여 삽질에 동참해주시면 감사하겠습니다,
자세한 시행착오내용 및 찾아봤던 Rollup 설정 자료, Sample 소스들을 첨부합니다.
https://www.notion.so/Rollup-e0736de4fc214ec0ba4e9eee5cab47ec

**Comment by jinsunee** [comment]
rollup.config.js 파일에서 아래처럼 시도해봐주실 수 있나요?
대부분의 라이브러리들은 버전문제도 있고 파일 크기가 너무 커서 겹칠만한것들이나 그런 라이브러리를 package.json 에서 peerDependencies에 넣어준다고 합니다. 
여기 있는 라이브러리들은 따로 외부옵션을 사용해야한다는 설정을 해야하는데 아마 이 문제때문이지 않을까 싶어요!

```
import external from "rollup-plugin-peer-deps-external";
...

export default [
    ...,
    external()
];
```

**Comment by chjjh0** [comment]
진선님 도와주셔서 감사합니다!!
es 형태로 번들링 및 배포 성공했습니다
좀 더 자세한 내용은 링크 참고 부탁드립니다~
https://www.notion.so/21-02-28-dff18e95a08643ce97703f6d1b835262

**Comment by jinsunee** [comment]
번들링된 파일만 npm에 올라가는 것으로 알고 있습니다.
 그래서 rollup 설정에도 `output`의 `file`에 번들링된 파일이 어디에 생성되어야하는지 관련한 경로를 설정할 수 있고 `npm publish` 명령어를 입력했을 때 `package.json`에 있는 main 필드를 보고 파일을 업로드하는 것으로 알고 있어요!

**Comment by chjjh0** [comment]
넵 테스트 결과 .npmignore 설정으로 번들링 된 파일만 올리는 걸로 처리했습니다
최신버전인 1.0.4 버전으로 받으시면 node_modules 에서 확인 가능합니다~
https://www.npmjs.com/package/react-button-from-junghun

**Comment by jinsunee** [comment]
고생많으셨습니다아~~~! ㅠㅠ
